 
name: Test and Build app

on:
  push:
    branches: [ develop ]  # Replace with your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run PHP Linter on all .php files
        run: |
          for file in $(find . -name "*.php"); do
            echo "Linting $file"
            php -l "$file"
          done
  