name: Test and Build app
env:
  APP_NAME: webapp  # Set this to the name of your Azure 
on:
  push:
    branches: [ develop ]  # Replace with your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run PHP Linter on all .php files in the webapp folder
        run: |
          for file in $(find ./webapp -name "*.php"); do
            echo "Linting $file"
            php -l "$file"
          done

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest -f Dockerfile-nginxv1 .
          docker push ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Connect in ssh to host
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull image from docker hub
        run: |
          docker pull ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest
      - name: Run container
        run: |
          docker run -d -p 80:80 ${{ secrets.DOCKER_USER }}/${{ env.APP_NAME }}:latest

      